services:
  webserver:
    image: quay.io/aclowes/yawn:latest
    command: ["yawn", "webserver"]
    environment:
      # secrets come from .env
      SENTRY_DSN:
      SECRET_KEY:
      DATABASE_URL:
      GUNICORN_CMD_ARGS: "-b 0.0.0.0:8000 --access-logformat '%(h)s %(l)s %(u)s %(t)s \"%(r)s\" %(s)s %(b)s \"%(f)s\" \"%(a)s\" %({Host}i)s %({X-Forwarded-Proto}i)s'"
      ALLOWED_HOSTS: ".yawn.live"
      VIRTUAL_HOST: yawn.live
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: yawn.live
      # KUBERNETES_POD_NAME is sent to sentry, map it?
    depends_on:
      - postgres
    expose:
      - 8000
    logging:
      driver: gcplogs

  worker:
    image: quay.io/aclowes/yawn:latest
    command: ["yawn", "worker"]
    environment:
      # secrets come from .env
      SENTRY_DSN:
      SECRET_KEY:
      DATABASE_URL:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp.json
      LUX_TOKEN:
      LUX_THERMOSTATS:
      SCE_USERNAME:
      SCE_PASSWORD:
      SCE_ACCOUNTS:
      GITHUB_TOKEN:
    secrets:
      - gcp.json
    depends_on:
      - postgres
    logging:
      driver: gcplogs

  postgres:
    image: postgres:11
    environment:
      # secrets come from .env
      POSTGRES_PASSWORD:
      POSTGRES_DB: yawn
      POSTGRES_USER: yawn
    expose:
      - 5432
    volumes:
      - /mnt/disks/database/postgres:/var/lib/postgresql/data
    logging:
      driver: gcplogs

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: gcplogs

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      DEFAULT_EMAIL: aclowes@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: gcplogs

  chatbot:
    build: chatbot
    security_opt:
      - seccomp=unconfined
    environment:
      # secrets come from .env
      OPENAI_API_KEY:
      GRADIO_SERVER_NAME: 0.0.0.0
      VIRTUAL_HOST: chat.bevibenewine.com
      VIRTUAL_PORT: 7860
      LETSENCRYPT_HOST: chat.bevibenewine.com
    expose:
      - 7860
    logging:
      driver: gcplogs  # not working for some reason

secrets:
  gcp.json:
    # manually pasted in sudo vi /mnt/stateful_partition/gcp.json
    # ignore the 'undefined secret file' warning, it is false
    file: /mnt/disks/database/gcp.json

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs: