# https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
#
# You must base64 encode these secrets before putting them in the file:
#     echo -n "admin" | base64

apiVersion: v1
kind: Secret
metadata:
  name: yawn-secrets
type: Opaque
data:
  # Ingress SSL certificate:
  tls.crt:
  tls.key:
  # Django cookie hashing key:
  SECRET_KEY:
  DATABASE_URL:
  POSTGRES_PASSWORD:
