# https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

apiVersion: v1
kind: Secret
metadata:
  name: yawn-secrets
type: Opaque
data:
  # Ingress SSL certificate:
  tls.crt:
  tls.key:
  # Django cookie hashing key:
  SECRET_KEY:
  POSTGRES_PASSWORD:
