apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yawn-webserver
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: yawn-webserver
    spec:
      containers:
      - name: yawn-webserver
        image: quay.io/aclowes/yawn-gke:latest
        # TODO run migrations on startup
        command: ["yawn", "webserver"]
        env:
        - name: GUNICORN_CMD_ARGS
          value: "-b 0.0.0.0:8000 --access-logformat '%(h)s %(l)s %(u)s %(t)s \"%(r)s\" %(s)s %(b)s \"%(f)s\" \"%(a)s\" %({Host}i)s %({X-Forwarded-Proto}i)s'"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: yawn-secrets
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: yawn-secrets
              key: SECRET_KEY
        ports:
        - containerPort: 8000
