apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yawn-worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: yawn-worker
    spec:
      containers:
      - name: yawn-worker
        image: quay.io/aclowes/yawn-gke:latest
        command: ["yawn", "worker"]
        ports:
        - containerPort: 8000
        env:
        - name: ALLOWED_HOSTS
          value: ".yawn.live"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: yawn-secrets
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: yawn-secrets
              key: SECRET_KEY
