apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yawn-webserver
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: yawn-webserver
    spec:
      containers:
      - name: yawn-webserver
        image: quay.io/aclowes/yawn-gke:latest
        command: ["yawn", "webserver"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: yawn-secrets
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: yawn-secrets
              key: SECRET_KEY
        ports:
        - containerPort: 8000
