apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yawn-worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: yawn-worker
    spec:
      containers:
      - name: yawn-worker
        image: quay.io/aclowes/yawn-gke:latest
        command: ["yawn", "worker"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: credentials-volume
          mountPath: /etc/credentials
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/gcp.json
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: yawn-secrets
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: yawn-secrets
              key: SECRET_KEY
      volumes:
      - name: credentials-volume
        secret:
          secretName: yawn-secrets
          items:
          - key: gcp.json
            path: gcp.json
